# Text for Frontend UI

SQL_MSG = """Hello! I'm a SQL assistant that can generate SQL queries from natural language descriptions. 
           Please provide me with your query in plain English, and I'll translate it into SQL for you.
           """

AI_MSG = """
        Hello! I'm an AI assistant specializing in summarizing SQL queries and their results. 
        Let me help bridge the gap between complex data and clear insights!
        """

SUFFIX_ERROR_V1 = """
                 \n Reply with instructions:  \n - \"yes\" to run previous query generated by SQL assistant.  
                 \n - \"skip\" to ask a new question.  \n - \"regen\" if wants to regenerate sql query.  
                 \n - new query if manual changes are required.    
                """

SUFFIX_ERROR_V2 = """ \n Reply with instructions:  \n - \"skip\" to ask a new question.  
                       \n - \"regen\" if wants to regenerate sql query.  \n - new query if manual changes are required.
                    """

STREAM_MSG = """**Here is the generated SQL Query.**  \n Reply with instructions:  \n - \"yes\" if run query.  
                \n - \"regen\" if wants to regenerate sql query.  \n - new query if manual changes are required.  \n ```  \n 
                """


STREAM_MSG_SCHEMA_MODE = """
                        **Here is the generated SQL Query.**  \n Reply with instructions:  \n - \"regen\" if wants to regenerate sql query.  
                        \n - new question if you are satisfied with the query!  \n ```  \n
                        """

MODEL_SETTINGS_MD = """
                    :exclamation: :grey[**You may modify the prompt, but please keep all placeholders (eg: :red[{input}] ) 
                    intact to ensure proper output generation**]    
                    """

SCHEMA_MODE_MD = """
                :exclamation: :grey[**Database schema mode only generates SQL queries from natural language and does not require any connection to database. 
                You are required to provide the database schema to use this mode.**]
                """

# LLM PROMPTS

PROMPT_SQL = """
            Generate a SQL query to answer [QUESTION]{input}[/QUESTION]
            
            ### Database Schema
            The query will run on a database with the following schema:
            {table_info}
            
            ### Chat History
            Relevant chat history between user and assistant:
            {history}
            
            ### Answer
            Given the database schema, here is the SQL query that [QUESTION]{input}[/QUESTION]
            [SQL]    
            """


PROMPT_REGEN_SQL = """### Task
                Given an original incorrect SQL query and a question, generate a CORRECT SQL query that can be executed on the provided database schema to answer [QUESTION]{input}[/QUESTION]
                The regenerated SQL query should learn from the mistakes in the original incorrect SQL query and strictly adhere to the database schema.
                    
                ### Database Schema
                Please note the table names, column names, data types, and any constraints or relationships between tables. Thoroughly understand the schema before generating the SQL query.
                The query will run on a database with the following schema:
                    
                {table_info}
                    
                ### Original Incorrect SQL Query
                {wrong_sql_query}
                    
                ### Answer
                Given that the database schema and your answer MUST different with original incorrect SQL query, here is the SQL query that [QUESTION]{input}[/QUESTION]
                [SQL]
                 """

PROMPT_REGEN_SQL_V2 = """### Task
            Given an original incorrect SQL query, a question, and a detailed database schema, generate a CORRECT SQL query that can be executed on the provided schema to answer the question. 
            The regenerated SQL query should learn from the mistakes in the original query and strictly adhere to the database schema.
            
            ### Database Schema
            The query will run on a database with the following schema:
            
            {table_info}
            
            ### Original Incorrect SQL Query
            
            {wrong_sql_query}
            
            ### Question
            [QUESTION]{input}[/QUESTION]
            
            ### Analysis of the Original Incorrect SQL Query
            [Provide a detailed analysis of the mistakes or issues in the original incorrect SQL query, such as:
            - Syntax errors
            - Incorrect table or column names
            - Misunderstanding of the schema or relationships
            - Logical errors or missing components
            - Violation of constraints or data types
            - Inefficient or suboptimal query structure]
            
            ### Requirements for the Regenerated SQL Query
            The regenerated SQL query should:
            1. Correctly answer the given question based on the database schema.
            2. Learn from the mistakes in the original incorrect SQL query and avoid repeating them.
            3. Strictly adhere to the database schema, using correct table and column names, respecting data types and constraints, and handling relationships appropriately.
            4. Follow best practices for SQL query structure, readability, and performance optimization.
            5. Include any necessary joins, filters, aggregations, or subqueries to retrieve the desired data.
            6. Ensure that the output is only the SQL query, without any additional text or explanation.
            7. Use the "ILIKE" operator more than the "=" operator to make the query case-insensitive for string comparisons.
            
            [SQL]
            """

PROMPT_RESPONSE = """
            You are a helpful assistant that will generate human-readable response for a question based on sql query and sql results.
            You MUST use ALL information provided in sql results below to generate human-readable response for question.
            Your response MUST NOT include any codes and be accurate and concise. Do not add on any additional information in your response.
            
            ### Chat History
            Relevant chat history between user and assistant:
            
            {history}
            
            ### Answer
            If the sql results is NONE, you MUST reply that you could not answer the question because sql results return nothing.
            
            question : {question}
            sql query : {query}
            sql results : {results}
            
            Human-readable response: 
            """

SCHEMA_PROMPT = """
        CREATE TABLE products (
	    product_id INTEGER PRIMARY KEY, -- Unique ID for each product
	    name VARCHAR(50), -- Name of the product
	    quantity INTEGER  -- Current quantity in stock
        );
        """